travis:
  secure:
    BINSTAR_TOKEN: Ov2D622v4sCJ5T7FzoA8eKHF3yKUF0GaMX598p3XlgvUrMran9bNRwAnER5h1/AhdK3o0Iq4f/iijT+3EqGpT5Ol5FhDZptN7ANAQbZiPJYi8MhESQ6RkxfvP/Fazm9JplUyAVS+xQmSGlfWDd1eNxLia2FgFIOGKO8qHjBPiCGh2Jf+3PfExQhIV3JHdYeH2uHMjVOnsZdKfpYK/uE8uraaoTVy6/0epyJF2MuV0iQVwJWaklYa7edeBIgOlaryF1D2Zs6N05riV/Ernq9/s8vDkcR/wnRE6xF++qBouD9ikwNQM7ugRL6SKlClrt0woad0/gZf1LGa82BVBbXMGJ1ZyKQKkY0CXpyWR4Cc4YiHLJkhrX8nuqrdPNjB4DzO/cCA+mVaClfcZr7BEOoIktyrlQKq/uC/hhBjWEdR2JyuwLrs5sSwv6HSjLYJMqfBBwaYrLWzL5UwUdW96iw6XSU5DbP3KDclDnp5y2nx8dVtPqvaOgCCn/Jg1rt3sGsd6MFi8QDa3qF54aaKWeM+hJnFAdzNoN8Eomb/ZXyUBhzMOoEYYZel2S+vya6wZcdjRMfzyJ7yZYMHwf/en5l7GOg+4trBB2fo5idMn9LPCG2nO/nrVQxC2Yq/I2wp5B3EEzKHGkPt7QBbGuDR67jk38Vy6BuYYPfkKte1qrmh6Tw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
