travis:
  secure:
    BINSTAR_TOKEN: LlRKWq3cYzCAYBFqNmZV12j8pCRMysRL1ZnD5K5guNks6sGJPqHCN6eAC2e44cb0VTvDWK6MOi7Z3Eo4kROQEuX68xZym/UlHhPedxEBwb+OTNSvOhgAl1pyXfHMWj+j/idSs7gPD72o42uUIqxImJYQeCjntKkoRRhg14HzQo2hFjwBqTUm7CcVh+Jf260jG7lvZB1MDfVVluRxTQ1QOhP2DnB5xSF0SD+kTeLz6kyQhtKwMb+Bu9CDICrUUjlc54BVxrP1ngPhSPjDLGwiHdwiaXzvjhsXL9Ah4OudmfAtjy2TnHqrK4G9/2SHD05YhvirMn936etNtuX++yJXsSpnMKOR+uMQtvuP1gQe9m2a/5ALBQ2k4igLUYvyTVxSmwPJPYnCRn9djjPJp6181Lhgsi1C9DMPm6HauncPjLtfjlmwcBFp5RWQ1FK9dCkSzSD3XzOIYYfAZM2KnbFvP/0fywln0uQ0dTUbNxJz5qiuZa6zKfpThs3sUjCd1TY/10dHl/uowDKz4MFCSMS74VXcQ2GIze12lANMnkczSNsHPG7I863GQfJP3dUznSnDg95FdT5rlXwc/jY5y2MXU6pxpNX3Co566sSJ9itelq+jmzyuiIEuSa1i6p0+OUcOBSyO3URy4cbs1ALmRdGg0yDKrwr/rhFwVnRQL01p3wE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
