travis:
  secure:
    BINSTAR_TOKEN: fox+Aihy24m8e4gdsqLJ/CDE6tlek7fW569qW7rwhJNv6Yqb9CX2MFMYV8Pgd3FuAkBTXhZ78eCYuHn4dxI0vIqZQHS3sKGtXACkvpxE3zNqUOLZexrz5Tin+K3z04FU6vDNzDHBBelzISN6qZZuwhXYzuEwxqOZkzar8ibtn6DFWmK60GY2IUxwWJ4SxEAji9M4/uXoLGal/iKsSdqXh8jTpNKjUkPJoArOsNdFew5LRnkKJLwVjucu97jY2HONamuL05RYbM69MHf3CoFKgUYg/aarLaQOc45CAHb3HUZahT9HAhNNKItQKDRDEv38BlY1fna8yJXh+MNmDbqD7BQPudc/qafm7p8sOB/l+wVp8gHrM2rs2mNVX0DqTTd8UXFSRJ4YcDQ28BqKDDWGXIvTifSo0ik5D3ujqbU+cm0C87IOdEOIGlTWoyJqWmEpKRU7ANO6M2Yr53fagiMPIQ/kKKd1Bgh23QqY5GTq/WBcMgjVBzoaRA5Xnym4LAWKedUqGVK5zTFTMhhMZjKQ7GJHBlQuaIqm8fEgx8V/Oil8OovUpzuBdVtP+3N7qnjSmHv4KdocAu4Q2xX13GAMDcQhRP8em4umCSiBB5ZJ4KaZy1y4Mwv6IURMoJ3kWGOZDS/CcFAizs8rV7nKPSTknEaCkTy7eFlHtbN9VbRlg4k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
